Update deploy.yaml

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -33,7 +33,11 @@ jobs:
         gcloud run deploy bike-rent \
           --image gcr.io/bike-rent-403120/bike-rent:$GITHUB_SHA \
           --platform managed \
-          --region us-central1  
+          --region us-central1
+        if [ $? -ne 0 ]; then
+          echo "Deployment to Cloud Run failed."
+          exit 1
+        fi
 
     - name: Debug Info
       run: |
